import localFont from "next/font/local";
import "../globals.css";
import Navbar from "@/Components/shared/navbar";
import Footer from "@/Components/shared/footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar></Navbar>
      <div>
        {children}
      </div>
      <Footer> </Footer>
    </div>
  );
}
